ChiquimundiCRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)
from django.urls import path, include
from leads.views import landing_page, SignupView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='home'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
]

if settings.DEBUG:
    urlpatterns += static('settings.STATIC_URL, document_root=settings.STATIC_ROOT')

agents/urls.py
from django.urls import path
from .views import (
    AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView
    )

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete'),
]

leads/urls.py
from django.urls import path
from .views import (
    LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, AssignAgentView, CategoryListView, CategoryDetailView, LeadCategoryUpdateView, CrearProformaView, crear_articulo
)

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name='list'),
    path('create/', LeadCreateView.as_view(), name='create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('<int:pk>/', LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('proforma/<int:proforma_id>/pdf/', CrearProformaView.as_view(), name='generate_pdf'),
    path('crear_proforma/', CrearProformaView.as_view(), name='crear_proforma'),
    path('create_article/', crear_articulo, name='crear_articulo'),
]

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from leads.models import Agent

User = get_user_model()

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = Agent
        fields = (
            'cedula',
            'nombre',
            'apellido',
            'telefono',
            'email',            
        )

agents/views.py
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, reverse
from leads.models import Agent, User
from .forms import AgentModelForm
from .mixins import OrganisorAndLoginRequiredMixin

User = get_user_model()

class AgentListView(OrganisorAndLoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)
    
    
class AgentCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm
    
    def get_success_url(self):
        return reverse("agents:agent-list")
    
    def form_valid(self, form):
        # Guarda el formulario de agente sin cometerlo a la base de datos
        agent = form.save(commit=False)
        
        # Obtiene o crea el usuario asociado al agente por su nombre
        user, created = User.objects.get_or_create(
            username=agent.nombre,
            defaults={
                'email': agent.email,
                'is_agent': True,
                'is_organisor': False,
            }
        )

        # Asigna el usuario al agente
        agent.user = user
        agent.organisation = self.request.user.userprofile
        agent.save()

        return super(AgentCreateView, self).form_valid(form)
    
    def form_invalid(self, form):
        return render(self.request, 'agents/agent_create_error.html')



class AgentDetailView(OrganisorAndLoginRequiredMixin, generic.DetailView):
    template_name = "agents/agent_detail.html"
    context_object_name = "agent"
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)
    
    
class AgentUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    form_class = AgentModelForm
    
    def get_success_url(self):
        return reverse("agents:agent-list")
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


class AgentDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_delete.html"
    context_object_name = "agent"
    
    def get_success_url(self):
        return reverse("agents:agent-list")
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

agents/templates/agents/agent_create.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

<div class="max-w-lg mx-auto mt-12">
    <a class="hover:text-blue-500" href="{% url 'agents:agent-list'%}">Regresar a la lista de agentes</a>
    <div class="max-w-lg mx-auto mt-2">
        <div class="py-5 border-t border-gray-200">
            <h1 class="text-4xl text-gray-800">Crear un nuevo Agente</h1>
        </div>
        <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md">Crear Nuevo agente de Venta</button>
        </form>
    </div>
</div>
{% endblock content %}

agents/templates/agents/agent_create_error.html
{% extends "base.html" %}
{% tailwind_filters %}
{% block content %}
<div class="container mx-auto my-10">
  <h2 class="text-2xl font-semibold mb-4">Error al crear un agente</h2>
  <p>Lo sentimos, hubo un problema al crear el agente. Por favor, verifica los datos ingresados y vuelve a intentarlo.</p>
  <a href="{% url 'agents:agent-create' %}" class="text-blue-500 hover:text-blue-600">Volver a la página de creación de agentes</a>
</div>
{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

<div class="max-w-lg mx-auto mt-12">
    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'agents:agent-list'%}">Regresar a la lista de agentes</a>
    </div>
    <h1 class="text-3xl text-gray-800 mt-3">Estás seguro que deseas eliminar este Agente de Venta?</h1>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form.crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md">Confirmar</button>
    </form>
</div>
{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %}
{% block content %}
<section class="text-gray-600 body-font">
    <div class="container p-10">
      <div class="w-full flex justify-center">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENTE DE VENTA</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{agent.user.username}}</h1>
          <div class="flex mb-4">
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Descripción</a>
            <a href="{% url 'agents:agent-update' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Actualizar</a>
            <a href="{% url 'agents:agent-delete' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Borrar</a>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">E-mail:</span>
            <span class="ml-auto text-gray-900"> {{agent.email}} </span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Contacto:</span>
            <span class="ml-auto text-gray-900"> {{agent.telefono}} </span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Fecha de ingreso</span>
            <span class="ml-auto text-gray-900"> {{agent.fecha_ingreso}} </span>
          </div>
          <div class="flex mt-6 justify-center">
            <a href="{% url 'agents:agent-list'%}" class="px-6 py-2 bg-indigo-500 hover:bg-indigo-600 text-white rounded-md focus:outline-none">
                  Regresa a la lista de agentes
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block content %}
  <section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
      <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
          <h1 class="text-4xl text-gray-800">Agentes</h1>
        </div>
        <div>
          <a class="text-gray-500 hover:text-blue-500" href="{% url 'agents:agent-create' %}">Crear un nuevo Agente</a>
        </div>
      </div>
      <div class="flex flex-wrap -m-4">
        {% for agent in object_list %}
        <div class="p-4 lg:w-1/2 md:w-full">
          <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                <circle cx="12" cy="7" r="4"></circle>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3"> 
                {{ agent.user.username }} {{ agent.apellido }}
              </h2>
              <div class="leading-relaxed text-base">Celular: {{agent.telefono}} </div>
              <div class="leading-relaxed text-base">Correo: {{agent.email}} </div>
              <a href="{% url 'agents:agent-detail' agent.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
                Ver detalle del agente de venta
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock content %}

agents/templates/agents/agent_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex justify-center">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENTE DE VENTA</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{ agent.user.username }}</h1>
          <div class="flex mb-4">
            <a href="{% url 'agents:agent-detail' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                Descripción
            </a>
            <a href="{% url 'agents:agent-update' agent.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                Actualizar
            </a>
          </div>
            <form method="POST">
            {% csrf_token %}   
            {{form|crispy}}
            <div class="flex md:mt-4 mt-2">
              <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" type="submit">Regresar a la lista de Leads</button>
          </div>
            <div class="flex mt-2">
                <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" type="submit">Guardar</button>
            </form>
            <a href="{% url 'agents:agent-delete' agent.pk %}" class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}