ChiquimundiCRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)
from django.urls import path, include
from leads.views import landing_page, SignupView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='home'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
]

if settings.DEBUG:
    urlpatterns += static('settings.STATIC_URL, document_root=settings.STATIC_ROOT')

agents/urls.py
from django.urls import path
from .views import (
    AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView
    )

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete'),
]

leads/urls.py
from django.urls import path
from .views import (
    LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, AssignAgentView, CategoryListView, CategoryDetailView, LeadCategoryUpdateView, CrearProformaView, crear_articulo
)

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name='list'),
    path('create/', LeadCreateView.as_view(), name='create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('<int:pk>/', LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('proforma/<int:proforma_id>/pdf/', CrearProformaView.as_view(), name='generate_pdf'),
    path('crear_proforma/', CrearProformaView.as_view(), name='crear_proforma'),
    path('create_article/', crear_articulo, name='crear_articulo'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRM CHIQUIMUNDI</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="icon" type="image" href="/static/images/chiquimundi.png">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/alpinejs"></script>

</head>

<body style="background: #edf2f7;">
    {% include "navbar.html" %}
    <main class="w-[calc(100%-256px)] ml-60">
        {% block content %}
        {% endblock content %}
    </main>
</body>

<script>
    function openNav() {
      document.getElementById("mySidebar").style.width = "250px";
      document.getElementById("main").style.marginLeft = "250px";
    }
    
    function closeNav() {
      document.getElementById("mySidebar").style.width = "0";
      document.getElementById("main").style.marginLeft= "0";
    }
</script>

</html>

templates/landing.html
{% extends "base.html" %}
{% block content %}
<section class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-col items-center justify-center">
    <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-3 object-cover object-center rounded" alt="Portada" src="/static/images/chiquimundi.png">
    <div class="w-full lg:w-2/3 md:w-1/2 flex flex-col items-center text-center">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">CHIQUIMUNDI CRM</h1>
      <div class="flex justify-center">
        {% if not request.user.is_authenticated %}
        <a href="{% url 'login' %}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg items-center justify-center m-5">Logear usuario</a>
        {% else %}
        <a href="{% url 'leads:list' %}"
          class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg items-center justify-center m-5">Lista de Leads</a>
        {% endif %}
        {% if request.user.is_autenticated %}
        <a href="{% url 'signup' %}"
          class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg items-center justify-center m-5">Registrar nuevo Usuario</a>
        {% endif %}
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/navbar.html
{% if request.user.is_authenticated %}
<div class="text-gray-600 body-font">
  <div class="fixed left-0 top-0 w-56 h-full p-4" style="background:#19293A;">
      <a href="{% url 'home' %}" class="flex items-center justify-center pb-4">
        <img class="w-32 h-32" src="/static/images/chiquimundi.png" alt="Logo Chiquimundi">
      </a>
      <ul>
        <li>
          {% if request.user.is_organisor %}
          <div class="mr-5">
            <a class="flex items-center py-2 px-4 text-gray-300 hover:bg-gray-950 hover:text-gray-100 rounded-md group-[.activate]:bg-gray-800 group-[.activate]:text-white" href="{% url 'leads:crear_articulo'%}">
              <i class="ri-add-circle-line"></i>
              <span class="ml-3 text-md">Crear Articulo</span>
            </a>
          </div>
          <div class="mr-5">
            <a class="flex items-center py-2 px-4 text-gray-300 hover:bg-gray-950 hover:text-gray-100 rounded-md group-[.activate]:bg-gray-800 group-[.activate]:text-white" href="{% url 'agents:agent-list' %}">
              <i class="ri-team-line"></i>
              <span class="ml-3 text-md">Agentes</span>
            </a>
            {% endif %}
          </div>
          <div class="mr-5">
            <a class="flex items-center py-2 px-4 text-gray-300 hover:bg-gray-950 hover:text-gray-100 rounded-md group-[.activate]:bg-gray-800 group-[.activate]:text-white" href="{% url 'leads:list' %}">
              <i class="ri-service-line"></i>
              <span class="ml-3 text-md">Leads</span>
            </a>
          </div>
          {% endif %}
        </li>
      </ul>
      
    <!-- condicionante -->
    {% if request.user.is_authenticated %}
    <div class="py-5">
      Logeado como: {{ request.user.username }}
      <a href="{% url 'logout' %}"
      class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Salir
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
      class="w-4 h-4 ml-1" viewBox="0 0 24 24">
      <path d="M5 12h14M12 5l7 7-7 7"></path>
    </svg>
    </a>
    {% else %}
    {% endif %}
  </div>
</div>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>